<?php

use Growcode\Omnibus\ViewModel\Product\HistoricalPrice;
use Magento\Catalog\Block\Product\View;

/** @var View $block */
/** @var HistoricalPrice $historicalPriceViewModel */

$historicalPriceViewModel = $block->getHistoricalPrice();
$product = $block->getProduct();
$quantity = $block->getQuantity();

if (!$historicalPriceViewModel->hasDiscount($product)) {
    return;
}

$regularPrice = $product->getPriceInfo()->getPrice('regular_price')->getValue();
$lowestHistoricalPrice = $historicalPriceViewModel->getLowestHistoricalPrice($block->getProduct()->getId());
$price = $lowestHistoricalPrice ? $lowestHistoricalPrice->getPrice() : $regularPrice;
$formattedPrice = $historicalPriceViewModel->formatPrice($price * $quantity);
?>
<script>
    function initHistoricalPrice<?= $product->getId(); ?>() {
        return {
            lowestHistoricalPrices: <?= $historicalPriceViewModel->getConfigurableProductLowestHistoricalPrices($product); ?>,
            formattedPrice: '<?= $formattedPrice; ?>',
            show: <?= $product->getTypeId() === 'configurable' ? 'false' : 'true'; ?>,
            eventListeners: {
                ['@configurable-selection-changed.window'](event) {
                    const { productIndex } = event.detail;
                    const price = this.lowestHistoricalPrices[productIndex];

                    if (price) {
                        this.formattedPrice = hyva.formatPrice(price);
                    }

                    this.show = !!price;
                },
            }
        }
    }
</script>
<div x-data="initHistoricalPrice<?= $product->getId(); ?>()" x-bind="eventListeners" x-cloak="" x-show="show">
    <span><?= __('Lowest price over the past 30 days:'); ?></span>
    <span x-html="formattedPrice"></span>
</div>
